import { mkdir, readdir, unlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { HostRoute } from "./store.ts";

const ROUTES_DIR = process.env.CASTLE_NGINX_ROUTES_DIR ?? "/etc/castle/nginx-routes";

const safeName = (hostname: string): string => {
  if (!/^[a-z0-9.-]+$/i.test(hostname)) throw new Error(`invalid hostname: ${hostname}`);
  return hostname;
};

const renderLocation = (pattern: string, backend: string, websocket: boolean): string => {
  const wsHeaders = websocket
    ? `        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection $connection_upgrade;\n`
    : "";
  return `    location ${pattern} {
        proxy_pass http://${backend};
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
${wsHeaders}    }`;
};

const render = (r: HostRoute): string => {
  const blocks: string[] = [];
  for (const loc of r.locations ?? []) {
    blocks.push(renderLocation(loc.pattern, loc.backend, loc.websocket));
  }
  blocks.push(renderLocation("/", r.backend, r.websocket));
  return `# generated by castled — do not edit by hand
server {
    listen 80;
    listen [::]:80;
    server_name ${r.hostname};

    client_max_body_size 1024m;

${blocks.join("\n\n")}
}
`;
};

export const ensureDir = async (): Promise<void> => {
  await mkdir(ROUTES_DIR, { recursive: true });
};

export const writeRoute = async (r: HostRoute): Promise<void> => {
  await ensureDir();
  await writeFile(join(ROUTES_DIR, `${safeName(r.hostname)}.conf`), render(r), { mode: 0o644 });
};

export const removeRoute = async (hostname: string): Promise<void> => {
  try {
    await unlink(join(ROUTES_DIR, `${safeName(hostname)}.conf`));
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
  }
};

export const sync = async (rows: HostRoute[]): Promise<void> => {
  await ensureDir();
  const want = new Set(rows.map((r) => `${r.hostname}.conf`));
  const existing = await readdir(ROUTES_DIR).catch(() => [] as string[]);
  for (const f of existing) {
    if (f.endsWith(".conf") && !want.has(f)) {
      await unlink(join(ROUTES_DIR, f)).catch(() => {});
    }
  }
  for (const r of rows) await writeRoute(r);
};

export const reload = async (): Promise<void> => {
  const proc = Bun.spawn(["sudo", "-n", "/bin/systemctl", "reload", "nginx"], {
    stdout: "pipe",
    stderr: "pipe",
  });
  const code = await proc.exited;
  if (code !== 0) {
    const err = await new Response(proc.stderr).text();
    throw new Error(`nginx reload failed (exit ${code}): ${err.trim()}`);
  }
};
