import type { AppTemplate } from "./types.ts";

export const catalog: AppTemplate[] = [
  {
    id: "ollama",
    name: "Ollama",
    description: "Run large language models locally with a simple HTTP API.",
    category: "AI",
    icon: "sparkles",
    docs: "https://github.com/ollama/ollama",
    multi: false,
    services: [
      {
        key: "ollama",
        role: "primary",
        image: "ollama/ollama:latest",
        ports: [{ container: 11434, primary: true }],
        volumes: [{ name: "data", target: "/root/.ollama" }],
        // q8_0 KV cache halves attention VRAM with negligible quality loss,
        // letting more layers/context stay on small (8GB-class) GPUs. Requires
        // flash attention, so force it on rather than relying on per-model auto.
        env: {
          OLLAMA_FLASH_ATTENTION: "1",
          OLLAMA_KV_CACHE_TYPE: "q8_0",
        },
        gpu: true,
      },
    ],
  },
  {
    id: "tangle",
    name: "Tangle",
    description: "Self-hosted git server with issues, PRs, and webhooks.",
    category: "Developer",
    icon: "git-branch",
    docs: "https://github.com/wess/tangle",
    multi: true,
    services: [
      {
        key: "db",
        role: "db",
        image: "postgres:16-alpine",
        env: {
          POSTGRES_DB: "tangle",
          POSTGRES_USER: "postgres",
          POSTGRES_PASSWORD: "${SECRET:POSTGRES_PASSWORD}",
        },
        volumes: [{ name: "pgdata", target: "/var/lib/postgresql/data" }],
        generateSecrets: ["POSTGRES_PASSWORD"],
      },
      {
        key: "app",
        role: "primary",
        image: "wess/tangle:main",
        ports: [{ container: 3001, primary: true }],
        env: {
          DATABASE_URL: "postgres://postgres:${SECRET:POSTGRES_PASSWORD}@${INSTANCE}-db:5432/tangle",
          SECRET: "${SECRET:SECRET}",
          APP_URL: "http://${INSTANCE}.local",
          STORAGE_DRIVER: "local",
          CASTLE_ADMIN_TOKEN: "${SECRET:CASTLE_ADMIN_TOKEN}",
          // OIDC relying-party config — Castle injects these at install time.
          SSO_ISSUER: "${INPUT:SSO_ISSUER}",
          SSO_CLIENT_ID: "${INPUT:SSO_CLIENT_ID}",
          SSO_CLIENT_SECRET: "${INPUT:SSO_CLIENT_SECRET}",
        },
        volumes: [
          { name: "repos", target: "/data/repos" },
          { name: "blobs", target: "/data/blobs" },
        ],
        dependsOn: ["db"],
        generateSecrets: ["SECRET", "CASTLE_ADMIN_TOKEN"],
      },
    ],
  },
  {
    id: "stohr",
    name: "Stohr",
    description: "Self-hosted cloud storage with sharing, S3 API, and WebDAV.",
    category: "Storage",
    icon: "cloud",
    docs: "https://github.com/wess/stohr",
    multi: true,
    services: [
      {
        key: "db",
        role: "db",
        image: "postgres:16-alpine",
        env: {
          POSTGRES_DB: "stohr",
          POSTGRES_USER: "postgres",
          POSTGRES_PASSWORD: "${SECRET:POSTGRES_PASSWORD}",
        },
        volumes: [{ name: "pgdata", target: "/var/lib/postgresql/data" }],
        generateSecrets: ["POSTGRES_PASSWORD"],
      },
      {
        key: "app",
        role: "primary",
        image: "wess/stohr:main",
        ports: [{ container: 3001, primary: true }],
        env: {
          DATABASE_URL: "postgres://postgres:${SECRET:POSTGRES_PASSWORD}@${INSTANCE}-db:5432/stohr",
          SECRET: "${SECRET:SECRET}",
          APP_URL: "http://${INSTANCE}.local",
          STORAGE_DRIVER: "local",
          CASTLE_ADMIN_TOKEN: "${SECRET:CASTLE_ADMIN_TOKEN}",
          // OIDC relying-party config — Castle injects these at install time.
          SSO_ISSUER: "${INPUT:SSO_ISSUER}",
          SSO_CLIENT_ID: "${INPUT:SSO_CLIENT_ID}",
          SSO_CLIENT_SECRET: "${INPUT:SSO_CLIENT_SECRET}",
        },
        volumes: [{ name: "blobs", target: "/data/blobs" }],
        dependsOn: ["db"],
        generateSecrets: ["SECRET", "CASTLE_ADMIN_TOKEN"],
      },
    ],
  },
  {
    id: "tandem",
    name: "Tandem",
    description: "Self-hosted team chat where humans and AI agents collaborate.",
    category: "AI",
    icon: "messages-square",
    docs: "https://github.com/wess/tandem",
    multi: true,
    services: [
      {
        key: "db",
        role: "db",
        image: "postgres:16-alpine",
        env: {
          POSTGRES_DB: "tandem",
          POSTGRES_USER: "postgres",
          POSTGRES_PASSWORD: "${SECRET:POSTGRES_PASSWORD}",
        },
        volumes: [{ name: "pgdata", target: "/var/lib/postgresql/data" }],
        generateSecrets: ["POSTGRES_PASSWORD"],
      },
      {
        key: "app",
        role: "primary",
        image: "wess/tandem:main",
        ports: [{ container: 3000, primary: true }],
        env: {
          DATABASE_URL: "postgres://postgres:${SECRET:POSTGRES_PASSWORD}@${INSTANCE}-db:5432/tandem",
          AUTH_SECRET: "${SECRET:AUTH_SECRET}",
          // OIDC relying-party config — Castle injects these at install time.
          SSO_ISSUER: "${INPUT:SSO_ISSUER}",
          SSO_CLIENT_ID: "${INPUT:SSO_CLIENT_ID}",
          SSO_CLIENT_SECRET: "${INPUT:SSO_CLIENT_SECRET}",
          // LLM providers — operator supplies at install (see prompts).
          ANTHROPIC_API_KEY: "${INPUT:ANTHROPIC_API_KEY}",
          OPENAI_API_KEY: "${INPUT:OPENAI_API_KEY}",
          OLLAMA_URL: "${INPUT:OLLAMA_URL}",
        },
        dependsOn: ["db"],
        generateSecrets: ["AUTH_SECRET"],
      },
    ],
    prompts: [
      {
        key: "ANTHROPIC_API_KEY",
        label: "Anthropic API key",
        type: "password",
        placeholder: "sk-ant-…",
        required: false,
      },
      {
        key: "OPENAI_API_KEY",
        label: "OpenAI API key",
        type: "password",
        placeholder: "sk-…",
        required: false,
      },
      {
        key: "OLLAMA_URL",
        label: "Ollama URL",
        type: "text",
        default: "http://ollama.local",
        required: false,
      },
    ],
  },
  {
    id: "jellyfin",
    name: "Jellyfin",
    description: "Free media server for movies, shows, music, and books.",
    category: "Media",
    icon: "film",
    docs: "https://jellyfin.org",
    multi: false,
    services: [
      {
        key: "jellyfin",
        role: "primary",
        image: "jellyfin/jellyfin:latest",
        ports: [{ container: 8096, primary: true }],
        volumes: [
          { name: "config", target: "/config" },
          { name: "cache", target: "/cache" },
        ],
      },
    ],
  },
  {
    id: "vaultwarden",
    name: "Vaultwarden",
    description: "Lightweight Bitwarden-compatible password manager.",
    category: "Security",
    icon: "key",
    docs: "https://github.com/dani-garcia/vaultwarden",
    multi: false,
    services: [
      {
        key: "vaultwarden",
        role: "primary",
        image: "vaultwarden/server:latest",
        ports: [{ container: 80, primary: true }],
        env: { WEBSOCKET_ENABLED: "true" },
        volumes: [{ name: "data", target: "/data" }],
      },
    ],
  },
  {
    id: "uptimekuma",
    name: "Uptime Kuma",
    description: "Self-hosted monitoring tool for websites and services.",
    category: "Monitoring",
    icon: "activity",
    docs: "https://github.com/louislam/uptime-kuma",
    multi: false,
    services: [
      {
        key: "uptimekuma",
        role: "primary",
        image: "louislam/uptime-kuma:1",
        ports: [{ container: 3001, primary: true }],
        volumes: [{ name: "data", target: "/app/data" }],
      },
    ],
  },
  {
    id: "homeassistant",
    name: "Home Assistant",
    description: "Open-source home automation hub.",
    category: "Home",
    icon: "house",
    docs: "https://www.home-assistant.io",
    multi: false,
    services: [
      {
        key: "homeassistant",
        role: "primary",
        image: "homeassistant/home-assistant:stable",
        ports: [{ container: 8123, primary: true }],
        volumes: [{ name: "config", target: "/config" }],
      },
    ],
  },
  {
    id: "adguard",
    name: "AdGuard Home",
    description: "Network-wide ad and tracker blocking via DNS.",
    category: "Network",
    icon: "shield",
    docs: "https://adguard.com/adguard-home.html",
    multi: false,
    services: [
      {
        key: "adguard",
        role: "primary",
        image: "adguard/adguardhome:latest",
        ports: [
          { container: 3000, primary: true },
          { container: 53, protocol: "udp" },
        ],
        volumes: [
          { name: "work", target: "/opt/adguardhome/work" },
          { name: "conf", target: "/opt/adguardhome/conf" },
        ],
      },
    ],
  },
  {
    id: "n8n",
    name: "n8n",
    description: "Workflow automation with hundreds of integrations.",
    category: "Automation",
    icon: "workflow",
    docs: "https://n8n.io",
    multi: false,
    services: [
      {
        key: "n8n",
        role: "primary",
        image: "n8nio/n8n:latest",
        ports: [{ container: 5678, primary: true }],
        env: { N8N_HOST: "${INSTANCE}.local", N8N_SECURE_COOKIE: "false" },
        volumes: [{ name: "data", target: "/home/node/.n8n" }],
      },
    ],
  },
  {
    id: "paperless",
    name: "Paperless-ngx",
    description: "Document management for scanned papers and PDFs.",
    category: "Productivity",
    icon: "file-text",
    docs: "https://docs.paperless-ngx.com",
    multi: true,
    services: [
      {
        key: "db",
        role: "db",
        image: "postgres:16-alpine",
        env: {
          POSTGRES_DB: "paperless",
          POSTGRES_USER: "paperless",
          POSTGRES_PASSWORD: "${SECRET:POSTGRES_PASSWORD}",
        },
        volumes: [{ name: "pgdata", target: "/var/lib/postgresql/data" }],
        generateSecrets: ["POSTGRES_PASSWORD"],
      },
      {
        key: "app",
        role: "primary",
        image: "ghcr.io/paperless-ngx/paperless-ngx:latest",
        ports: [{ container: 8000, primary: true }],
        env: {
          PAPERLESS_DBHOST: "${INSTANCE}-db",
          PAPERLESS_DBUSER: "paperless",
          PAPERLESS_DBPASS: "${SECRET:POSTGRES_PASSWORD}",
          PAPERLESS_SECRET_KEY: "${SECRET:SECRET}",
          PAPERLESS_URL: "http://${INSTANCE}.local",
        },
        volumes: [
          { name: "data", target: "/usr/src/paperless/data" },
          { name: "media", target: "/usr/src/paperless/media" },
        ],
        dependsOn: ["db"],
        generateSecrets: ["SECRET"],
      },
    ],
  },
];

export const findApp = (id: string): AppTemplate | undefined => catalog.find((a) => a.id === id);
