#!/usr/bin/env bash
# Server-side install of Castle. Expects:
#   /tmp/castle.tar.gz        - the build tarball
#   /opt/services/.env        - shared services env (CASTLE_DB_PASSWORD etc.)
#   /tmp/castle-nginx/        - the nginx site templates (castle/tangle/storage)
set -euo pipefail

TARBALL=${TARBALL:-/tmp/castle.tar.gz}
NGINX_TEMPLATES=${NGINX_TEMPLATES:-/tmp/castle-nginx}
INSTALL_DIR=/opt/castle
CONFIG_DIR=/etc/castle
DATA_DIR=/var/lib/castle
ENV_FILE=$CONFIG_DIR/castle.env
UNIT_FILE=/etc/systemd/system/castled.service
SHARED_ENV=/etc/castle-services/services.env
NGINX_MAP=/etc/nginx/conf.d/castle-upgrade.conf

log() { echo "==> $*"; }

if [ "$(id -u)" -ne 0 ]; then
  echo "must run as root (sudo)"
  exit 1
fi

if ! command -v nginx >/dev/null 2>&1; then
  log "installing nginx"
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends nginx
fi

log "extracting to $INSTALL_DIR"
mkdir -p "$INSTALL_DIR" "$CONFIG_DIR" "$DATA_DIR"
rm -rf "$INSTALL_DIR/web" "$INSTALL_DIR/server"
tar -C "$INSTALL_DIR" -xzf "$TARBALL"
chown -R wess:wess "$INSTALL_DIR" "$DATA_DIR"
chmod 0755 "$INSTALL_DIR"

# Pick up the postgres password generated by services-install.sh.
CASTLE_DB_PASSWORD=""
if [ -f "$SHARED_ENV" ]; then
  # shellcheck disable=SC1090
  CASTLE_DB_PASSWORD=$(grep -E '^CASTLE_DB_PASSWORD=' "$SHARED_ENV" | cut -d= -f2-)
fi
if [ -z "$CASTLE_DB_PASSWORD" ]; then
  echo "missing CASTLE_DB_PASSWORD — run scripts/services-install.sh first"
  exit 1
fi
DB_URL="postgres://castle:${CASTLE_DB_PASSWORD}@127.0.0.1:5432/castle"

if [ ! -f "$ENV_FILE" ]; then
  log "writing $ENV_FILE"
  SECRET=$(head -c 48 /dev/urandom | base64 | tr -d '\n+/=' | head -c 48)
  ADMIN_PW=$(head -c 18 /dev/urandom | base64 | tr -d '+/=' | head -c 18)
  cat > "$ENV_FILE" <<EOF
PORT=4280
HOST=127.0.0.1
DOCKER_SOCKET=/var/run/docker.sock
DATABASE_URL=$DB_URL
SECRET=$SECRET
WEB_ROOT=$INSTALL_DIR/web
WEB_ORIGIN=*
CASTLE_ADMIN_EMAIL=wess@castle.local
CASTLE_ADMIN_PASSWORD=$ADMIN_PW
EOF
  chown root:wess "$ENV_FILE"
  chmod 0640 "$ENV_FILE"
  echo "==> generated admin password: $ADMIN_PW"
else
  # Existing install — make sure HOST/DB are up-to-date.
  sed -i 's|^HOST=.*|HOST=127.0.0.1|' "$ENV_FILE"
  if grep -q '^DATABASE_PATH=' "$ENV_FILE"; then
    sed -i '/^DATABASE_PATH=/d' "$ENV_FILE"
  fi
  if grep -q '^DATABASE_URL=' "$ENV_FILE"; then
    sed -i "s|^DATABASE_URL=.*|DATABASE_URL=$DB_URL|" "$ENV_FILE"
  else
    echo "DATABASE_URL=$DB_URL" >> "$ENV_FILE"
  fi
fi

log "writing $UNIT_FILE"
cat > "$UNIT_FILE" <<EOF
[Unit]
Description=Castle daemon
After=network-online.target docker.service
Wants=network-online.target

[Service]
Type=simple
User=wess
Group=wess
SupplementaryGroups=docker
EnvironmentFile=$ENV_FILE
ExecStart=/usr/local/bin/bun run $INSTALL_DIR/server/castled.js
Restart=on-failure
RestartSec=3
WorkingDirectory=$INSTALL_DIR
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

if [ -d "$NGINX_TEMPLATES" ]; then
  log "installing nginx site configs"
  install -m 0644 "$NGINX_TEMPLATES/castle.conf" /etc/nginx/sites-available/castle
  install -m 0644 "$NGINX_TEMPLATES/tangle.conf" /etc/nginx/sites-available/tangle
  install -m 0644 "$NGINX_TEMPLATES/storage.conf" /etc/nginx/sites-available/storage
  ln -sf /etc/nginx/sites-available/castle  /etc/nginx/sites-enabled/castle
  ln -sf /etc/nginx/sites-available/tangle  /etc/nginx/sites-enabled/tangle
  ln -sf /etc/nginx/sites-available/storage /etc/nginx/sites-enabled/storage
  # Drop legacy / inline site that's been superseded.
  rm -f /etc/nginx/sites-enabled/default
fi

if [ ! -f "$NGINX_MAP" ]; then
  cat > "$NGINX_MAP" <<'EOF'
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
EOF
fi

log "provisioning castle-managed nginx routes directory"
mkdir -p /etc/castle/nginx-routes
chown wess:wess /etc/castle/nginx-routes
chmod 0755 /etc/castle/nginx-routes

if [ ! -f /etc/nginx/conf.d/castle-routes.conf ]; then
  cat > /etc/nginx/conf.d/castle-routes.conf <<'EOF'
# Castle-managed dynamic vhosts (written by castled)
include /etc/castle/nginx-routes/*.conf;
EOF
fi

cat > /usr/local/bin/castle-nginx-site <<'EOF'
#!/usr/bin/env bash
# Manage nginx sites-enabled symlinks. Invoked by castled via sudo.
set -euo pipefail
if [ "$#" -ne 2 ]; then
  echo "usage: $(basename "$0") enable|disable <name>" >&2
  exit 1
fi
ACTION=$1
NAME=$2
if ! [[ "$NAME" =~ ^[a-zA-Z0-9._-]+$ ]]; then
  echo "invalid site name" >&2
  exit 1
fi
case "$ACTION" in
  enable)
    if [ ! -f /etc/nginx/sites-available/"$NAME" ]; then
      echo "no such site: $NAME" >&2
      exit 1
    fi
    ln -sf /etc/nginx/sites-available/"$NAME" /etc/nginx/sites-enabled/"$NAME"
    ;;
  disable)
    rm -f /etc/nginx/sites-enabled/"$NAME"
    ;;
  *)
    echo "unknown action: $ACTION" >&2
    exit 1
    ;;
esac
EOF
chmod 0755 /usr/local/bin/castle-nginx-site

cat > /etc/sudoers.d/castle-nginx <<'EOF'
wess ALL=(root) NOPASSWD: /bin/systemctl reload nginx
wess ALL=(root) NOPASSWD: /usr/local/bin/castle-nginx-site
EOF
chmod 0440 /etc/sudoers.d/castle-nginx

log "validating nginx config"
nginx -t

log "reloading systemd + nginx"
systemctl daemon-reload
systemctl enable castled.service
systemctl restart castled.service
systemctl enable nginx
systemctl restart nginx
sleep 1
systemctl is-active castled.service
systemctl is-active nginx

log "done"
